"""DSP-only SPIHT deployment packager.

Produces a self-contained, weightless deploy package for a SPIHT codec:

* ``deploy_manifest.json`` — top-level manifest with ``family: "spiht"``,
  codec parameters, scorecard summary, and a listing of artifacts.
* ``spiht_config.json`` — codec parameters in a standalone, language-
  neutral form (mirrors what a C integrator needs).
* ``sample_stimulus.npz`` — license-safe synthetic frames generated via
  :func:`compressionkit.export.stimulus.generate_stimulus`.
* ``reference_vectors.npz`` — encode/decode round-trip vectors that
  consumers (Python and C) can use to confirm bit-exact behavior.
* ``spiht_app_config.h`` — generated, codec-specific operating-point
  macros (frame size, levels, max bits, AC flag, wavelet name). Drop-in
  header for a C integrator that already has the SPIHT algorithm sources
  (shipped separately as its own C module).
* ``model_card.json`` — optional ML-style card with provenance and
  reproduction notes.
* ``scorecard.json`` — optional, frozen evaluation summary.
* ``README.md`` — short integration guide.

The package is fully reproducible from a config and a scorecard; no
trained weights are produced because SPIHT has none. The deployable
artifact is the **bitstream contract**, the operating-point parameters,
and reference vectors — the SPIHT algorithm C sources live in a separate
C-module repository and are not vendored here.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from compressionkit.export.release import write_checksums, write_json, write_model_card, write_scorecard_artifact
from compressionkit.export.stimulus import generate_stimulus
from compressionkit.runtime.base import MANIFEST_VERSION, EncodedFrame
from compressionkit.runtime.spiht import SpihtCodec

logger = logging.getLogger(__name__)

__all__ = [
    "SpihtDeploymentArtifacts",
    "export_spiht_deploy",
    "refresh_hybrid_reference_vectors",
]


@dataclass
class SpihtDeploymentArtifacts:
    """Paths to all exported SPIHT deploy artifacts."""

    output_dir: Path
    manifest: Path = field(default_factory=Path)
    spiht_config: Path = field(default_factory=Path)
    sample_stimulus: Path = field(default_factory=Path)
    reference_vectors: Path = field(default_factory=Path)
    app_config_header: Path = field(default_factory=Path)
    model_card: Path = field(default_factory=Path)
    scorecard: Path = field(default_factory=Path)
    codec_spec: Path = field(default_factory=Path)
    readme: Path = field(default_factory=Path)

    checksums: Path = field(default_factory=Path)

    def as_dict(self) -> dict[str, str]:
        """Return artifact paths relative to ``output_dir``."""
        return {
            k: str(v.relative_to(self.output_dir)) if v != Path() else ""
            for k, v in self.__dict__.items()
            if k != "output_dir" and isinstance(v, Path)
        }


def _render_app_config_header(
    *,
    frame_size: int,
    levels: int,
    max_bits: int,
    use_ac: bool,
    wavelet: str,
    modality: str,
    target_cr: float,
) -> str:
    """Render the codec-specific C header with operating-point macros.

    The header carries only the application-level parameters — no
    algorithm implementation. Pair it with the SPIHT C module shipped
    from its own repository.
    """
    ac_flag = 1 if use_ac else 0
    guard = "COMPRESSIONKIT_SPIHT_APP_CONFIG_H"
    return f"""/*
 * SPIHT codec deploy configuration for {modality.upper()} @ {target_cr:g}x.
 *
 * Generated by compressionkit.export.spiht_deploy.export_spiht_deploy().
 * Operating-point macros only — pair this with the SPIHT C algorithm
 * sources shipped from a separate C-module repository.
 */
#ifndef {guard}
#define {guard}

#define APP_SPIHT_FRAME_SIZE   {frame_size}
#define APP_SPIHT_LEVELS       {levels}
#define APP_SPIHT_MAX_BITS     {max_bits}
#define APP_SPIHT_MAX_BYTES    {(max_bits + 7) // 8}
#define APP_SPIHT_USE_AC       {ac_flag}
#define APP_SPIHT_WAVELET_NAME "{wavelet}"
#define APP_SPIHT_MODALITY     "{modality}"

#endif /* {guard} */
"""


def _render_readme(
    *,
    modality: str,
    target_cr: float,
    wavelet: str,
    levels: int,
    frame_size: int,
    sample_rate: int,
    max_bits: int,
    use_ac: bool,
) -> str:
    ac_note = "arithmetic coding enabled" if use_ac else "raw SPIHT bitstream"
    return f"""# compressionKIT SPIHT deploy — {modality.upper()} @ {target_cr:g}x

DSP-only codec. There are no trained weights; this package ships the
bitstream contract and operating-point parameters. The SPIHT algorithm
C sources are shipped separately as their own C module.

## Operating point

| Field         | Value           |
|---------------|-----------------|
| Modality      | {modality.upper()} |
| Sample rate   | {sample_rate} Hz |
| Frame size    | {frame_size} samples |
| Wavelet       | `{wavelet}` |
| DWT levels    | {levels} |
| Target CR     | {target_cr:g}× |
| Bit budget    | {max_bits} bits/frame |
| Entropy coder | {ac_note} |

## Files

* `deploy_manifest.json` — top-level manifest (`family: "spiht"`).
* `spiht_config.json` — codec parameters (language-neutral).
* `sample_stimulus.npz` — synthetic frames (`stimulus`, `(N, frame_size)`).
* `reference_vectors.npz` — encode/decode round-trip vectors.
* `spiht_app_config.h` — codec-specific defines for this CR (no algorithm).
* `model_card.json`, `scorecard.json` — optional metadata.

## Python quickstart

```python
from compressionkit.runtime import load_codec

codec = load_codec("./")
frame = ...  # (frame_size,) float32
enc = codec.compress(frame)
recon = codec.decompress(enc)
```

## C integration

Include `spiht_app_config.h` from this package alongside the SPIHT C
algorithm sources (shipped from a separate C-module repository).

```c
#include "spiht_app_config.h"  /* operating-point macros */
#include "spiht.h"             /* algorithm; from C-module repo */

float frame[APP_SPIHT_FRAME_SIZE];
uint8_t bitstream[APP_SPIHT_MAX_BYTES];
/* ... fill frame from sensor ... */
size_t nbits = spiht_encode_frame(&enc, bitstream, APP_SPIHT_MAX_BITS);
```
"""


def _encode_reference_vectors(codec, stimulus: np.ndarray, output_dir: Path) -> Path:
    """Round-trip ``stimulus`` through ``codec`` and write ``reference_vectors.npz``.

    ``codec`` only needs to satisfy the :class:`~compressionkit.runtime.base.Codec`
    duck-type (``compress``/``decompress``) — this is shared by the DSP-only
    :class:`SpihtCodec` backend and the composed
    :class:`~compressionkit.runtime.hybrid.HybridSpihtCodec`, so callers can
    compute reference vectors against whichever pipeline actually ships.
    """
    logger.info("Computing reference encode/decode vectors...")
    payloads: list[np.ndarray] = []
    nbits_arr = np.zeros(stimulus.shape[0], dtype=np.int32)
    reconstructions = np.zeros_like(stimulus)
    for i, frame in enumerate(stimulus):
        enc: EncodedFrame = codec.compress(frame)
        if isinstance(enc.payload, (bytes, bytearray)):
            payload_bytes = bytes(enc.payload)
        elif isinstance(enc.payload, np.ndarray):
            payload_bytes = enc.payload.astype(np.uint8).tobytes()
        else:
            payload_bytes = bytes(enc.payload)
        payloads.append(np.frombuffer(payload_bytes, dtype=np.uint8))
        nbits_arr[i] = int(enc.nbits)
        reconstructions[i] = codec.decompress(enc)

    # Pack ragged payloads into a fixed-width 2D uint8 array (zero-padded to the
    # longest payload) plus a parallel `payload_lengths` array recording each
    # payload's true byte length, so consumers can slice `packed[i, :length]`.
    max_len = max((p.size for p in payloads), default=0)
    packed = np.zeros((len(payloads), max_len), dtype=np.uint8)
    payload_lengths = np.zeros(len(payloads), dtype=np.int32)
    for i, p in enumerate(payloads):
        packed[i, : p.size] = p
        payload_lengths[i] = p.size

    reference_vectors_path = output_dir / "reference_vectors.npz"
    np.savez_compressed(
        reference_vectors_path,
        input_frames=stimulus,
        bitstreams=packed,
        bitstream_lengths_bytes=payload_lengths,
        nbits=nbits_arr,
        reconstructions=reconstructions,
    )
    return reference_vectors_path


def refresh_hybrid_reference_vectors(deploy_dir: str | Path) -> Path:
    """Recompute ``reference_vectors.npz`` for an assembled hybrid deploy package.

    ``export_spiht_deploy`` only ever sees the bare SPIHT backend codec, so
    the reference vectors it writes reflect denoiser-OFF encode/decode. Call
    this *after* the hybrid package is fully assembled (denoiser staged,
    ``hybrid_manifest.json`` written, ``deploy_manifest.json``/``codec_spec.json``
    ``family`` patched to ``"hybrid"``) to overwrite ``reference_vectors.npz``
    with vectors computed through the real hybrid (denoise -> SPIHT) pipeline,
    reusing the same synthetic frames already staged in ``sample_stimulus.npz``.
    Also regenerates ``checksums.json`` since the reference vectors changed.

    Args:
        deploy_dir: A hybrid deploy directory (``family == "hybrid"``).

    Returns:
        Path to the rewritten ``reference_vectors.npz``.
    """
    from compressionkit.runtime.hybrid import HybridSpihtCodec

    deploy_dir = Path(deploy_dir)
    codec = HybridSpihtCodec.from_deploy_dir(deploy_dir)
    stimulus = np.load(deploy_dir / "sample_stimulus.npz")["stimulus"].astype(np.float32, copy=False)
    ref_path = _encode_reference_vectors(codec, stimulus, deploy_dir)
    write_checksums(deploy_dir)
    return ref_path


def export_spiht_deploy(
    codec: SpihtCodec,
    *,
    output_dir: str | Path,
    model_name: str | None = None,
    model_version: str = "1.0",
    num_stimulus_samples: int = 8,
    stimulus_seed: int = 42,
    model_card_info: dict | None = None,
    scorecard_summary: dict | None = None,
) -> SpihtDeploymentArtifacts:
    """Export a SPIHT codec to a self-contained deploy directory.

    Args:
        codec: Hydrated :class:`SpihtCodec` describing the operating point.
        output_dir: Directory to write all deploy artifacts into.
        model_name: Override for the manifest ``model_name`` (defaults to
            ``codec.name``).
        model_version: Semantic version string written to the manifest.
        num_stimulus_samples: How many synthetic frames to generate.
        stimulus_seed: RNG seed for the synthetic stimulus.
        model_card_info: Optional dict merged into ``model_card.json``.
        scorecard_summary: Optional dict written to ``scorecard.json``.

    Returns:
        :class:`SpihtDeploymentArtifacts` with paths to every file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = SpihtDeploymentArtifacts(output_dir=output_dir)

    name = model_name or codec.name
    # Source of truth for codec parameters is the typed SpihtCodecConfig.
    cfg = codec.config.model_dump()
    # ``max_bits`` is derived (not part of the typed config) but is needed
    # by both the C header and consumers comparing against the bitstream.
    cfg["max_bits"] = codec.max_bits

    artifacts.codec_spec = output_dir / "codec_spec.json"
    artifacts.manifest = output_dir / "deploy_manifest.json"
    artifacts.checksums = output_dir / "checksums.json"

    # 1. Synthetic stimulus + reference vectors (round-trip through Python ref).
    logger.info("Generating synthetic stimulus (%d frames)...", num_stimulus_samples)
    stimulus = generate_stimulus(
        modality=codec.modality,
        num_samples=num_stimulus_samples,
        frame_size=codec.frame_size,
        sample_rate=codec.sample_rate,
        seed=stimulus_seed,
    ).astype(np.float32, copy=False)

    artifacts.sample_stimulus = output_dir / "sample_stimulus.npz"
    np.savez_compressed(artifacts.sample_stimulus, stimulus=stimulus)

    artifacts.reference_vectors = _encode_reference_vectors(codec, stimulus, output_dir)

    # 2. spiht_config.json (language-neutral parameters).
    artifacts.spiht_config = output_dir / "spiht_config.json"
    write_json(artifacts.spiht_config, cfg)

    # 3. Operating-point header (parameters only; algorithm lives elsewhere).
    artifacts.app_config_header = output_dir / "spiht_app_config.h"
    artifacts.app_config_header.write_text(
        _render_app_config_header(
            frame_size=codec.frame_size,
            levels=codec.levels,
            max_bits=codec.max_bits,
            use_ac=codec.use_ac,
            wavelet=codec.wavelet,
            modality=codec.modality,
            target_cr=codec.target_cr,
        )
    )

    # 4. Optional model card / scorecard.
    if model_card_info is not None:
        artifacts.model_card = write_model_card(
            output_dir,
            model_name=name,
            model_version=model_version,
            model_card_info=model_card_info,
        )
    if scorecard_summary is not None:
        artifacts.scorecard = write_scorecard_artifact(output_dir, scorecard_summary)

    # 5. Canonical runtime hydration spec.
    codec_spec = {
        "family": "spiht",
        "method": "dsp",
        "modality": codec.modality,
        "sample_rate": codec.sample_rate,
        "frame_size": codec.frame_size,
        "compression_ratio": codec.target_cr,
        "experiment_id": model_card_info.get("experiment_id") if model_card_info else None,
        "run_name": model_card_info.get("run_name") if model_card_info else None,
        "package_version": model_version,
        "packet_contract": {
            "payload_type": "uint8_bitstream",
            "nbits_field": True,
            "byte_order": "little-endian-byte-array",
        },
        "codec": cfg,
    }
    write_json(artifacts.codec_spec, codec_spec)

    # 6. README.
    artifacts.readme = output_dir / "README.md"
    artifacts.readme.write_text(
        _render_readme(
            modality=codec.modality,
            target_cr=codec.target_cr,
            wavelet=codec.wavelet,
            levels=codec.levels,
            frame_size=codec.frame_size,
            sample_rate=codec.sample_rate,
            max_bits=codec.max_bits,
            use_ac=codec.use_ac,
        )
    )

    # 7. Top-level manifest tying everything together.
    manifest = {
        "manifest_version": MANIFEST_VERSION,
        "package_version": model_version,
        "family": "spiht",
        "method": "dsp",
        "modality": codec.modality,
        "experiment_id": model_card_info.get("experiment_id") if model_card_info else None,
        "run_name": model_card_info.get("run_name") if model_card_info else None,
        "compression_ratio": codec.target_cr,
        "spec": artifacts.codec_spec.name,
        "scorecard": artifacts.scorecard.name if artifacts.scorecard != Path() else None,
        "checksums": artifacts.checksums.name,
        "model_name": name,
        "model_version": model_version,
        "codec": cfg,
        "artifacts": artifacts.as_dict(),
        "model_card": model_card_info or {},
        "scorecard_summary": scorecard_summary or {},
    }
    write_json(artifacts.manifest, manifest)

    # 8. File-integrity manifest.
    artifacts.checksums = write_checksums(output_dir)

    logger.info("SPIHT deploy package written to %s", output_dir)
    return artifacts
