"""DSP-only SPIHT deployment packager.

Produces a self-contained, weightless deploy package for a SPIHT codec:

* ``deploy_manifest.json`` — top-level manifest with ``family: "spiht"``,
  codec parameters, scorecard summary, and a listing of artifacts.
* ``spiht_config.json`` — codec parameters in a standalone, language-
  neutral form (mirrors what the C side needs).
* ``sample_stimulus.npz`` — license-safe synthetic frames generated via
  :func:`compressionkit.export.stimulus.generate_stimulus`.
* ``reference_vectors.npz`` — encode/decode round-trip vectors that
  consumers (Python and C) can use to confirm bit-exact behavior.
* ``c_sources/spiht.c``, ``c_sources/spiht.h`` — verbatim copies of the
  portable C99 reference under ``csrc/spiht/``.
* ``c_sources/spiht_app_config.h`` — generated codec-specific defines
  (frame size, levels, max bits, AC flag, wavelet name).
* ``model_card.json`` — optional ML-style card with provenance and
  reproduction notes.
* ``scorecard.json`` — optional, frozen evaluation summary.
* ``README.md`` — short integration guide.

The package is fully reproducible from a config and a scorecard; no
trained weights are produced because SPIHT has none. The deployable
artifact is the **bitstream contract** plus the C source.
"""

from __future__ import annotations

import json
import logging
import shutil
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from compressionkit.export.stimulus import generate_stimulus
from compressionkit.runtime.base import MANIFEST_VERSION, EncodedFrame
from compressionkit.runtime.spiht import SpihtCodec

logger = logging.getLogger(__name__)

__all__ = [
    "SpihtDeploymentArtifacts",
    "export_spiht_deploy",
]

# Path to the vendored C99 SPIHT sources.
# NOTE: This requires running from a source checkout; csrc/ is not included
# in installed wheels. A FileNotFoundError at export time indicates a
# non-editable install — run from the repository root instead.
_C_SOURCE_DIR = Path(__file__).resolve().parents[2] / "csrc" / "spiht"
_C_SOURCE_FILES = ("spiht.c", "spiht.h")


@dataclass
class SpihtDeploymentArtifacts:
    """Paths to all exported SPIHT deploy artifacts."""

    output_dir: Path
    manifest: Path = field(default_factory=Path)
    spiht_config: Path = field(default_factory=Path)
    sample_stimulus: Path = field(default_factory=Path)
    reference_vectors: Path = field(default_factory=Path)
    c_sources_dir: Path = field(default_factory=Path)
    app_config_header: Path = field(default_factory=Path)
    model_card: Path = field(default_factory=Path)
    scorecard: Path = field(default_factory=Path)
    readme: Path = field(default_factory=Path)

    def as_dict(self) -> dict[str, str]:
        """Return artifact paths relative to ``output_dir``."""
        return {
            k: str(v.relative_to(self.output_dir)) if v != Path() else ""
            for k, v in self.__dict__.items()
            if k != "output_dir" and isinstance(v, Path)
        }


def _render_app_config_header(
    *,
    frame_size: int,
    levels: int,
    max_bits: int,
    use_ac: bool,
    wavelet: str,
    modality: str,
    target_cr: float,
) -> str:
    """Render the codec-specific C header that pairs with vendored ``spiht.h``."""
    ac_flag = 1 if use_ac else 0
    guard = "COMPRESSIONKIT_SPIHT_APP_CONFIG_H"
    return f"""/*
 * SPIHT codec deploy configuration for {modality.upper()} @ {target_cr:g}x.
 *
 * Generated by compressionkit.export.spiht_deploy.export_spiht_deploy().
 * Pair this with the vendored ``spiht.c`` / ``spiht.h`` in this folder.
 * The vendored ``spiht.h`` carries compile-time upper bounds
 * (SPIHT_MAX_COEFFS, SPIHT_MAX_LEVELS, SPIHT_MAX_BITSTREAM_BYTES); the
 * application-level values below are the *actual* operating point.
 */
#ifndef {guard}
#define {guard}

#define APP_SPIHT_FRAME_SIZE   {frame_size}
#define APP_SPIHT_LEVELS       {levels}
#define APP_SPIHT_MAX_BITS     {max_bits}
#define APP_SPIHT_MAX_BYTES    {(max_bits + 7) // 8}
#define APP_SPIHT_USE_AC       {ac_flag}
#define APP_SPIHT_WAVELET_NAME "{wavelet}"
#define APP_SPIHT_MODALITY     "{modality}"

#include "spiht.h"

#if APP_SPIHT_FRAME_SIZE > SPIHT_MAX_COEFFS
#  error "APP_SPIHT_FRAME_SIZE exceeds SPIHT_MAX_COEFFS in spiht.h; rebuild spiht.h with larger bounds."
#endif
#if APP_SPIHT_LEVELS > SPIHT_MAX_LEVELS
#  error "APP_SPIHT_LEVELS exceeds SPIHT_MAX_LEVELS in spiht.h."
#endif
#if APP_SPIHT_MAX_BYTES > SPIHT_MAX_BITSTREAM_BYTES
#  error "APP_SPIHT_MAX_BYTES exceeds SPIHT_MAX_BITSTREAM_BYTES in spiht.h."
#endif

#endif /* {guard} */
"""


def _render_readme(
    *,
    modality: str,
    target_cr: float,
    wavelet: str,
    levels: int,
    frame_size: int,
    sample_rate: int,
    max_bits: int,
    use_ac: bool,
) -> str:
    ac_note = "arithmetic coding enabled" if use_ac else "raw SPIHT bitstream"
    return f"""# compressionKIT SPIHT deploy — {modality.upper()} @ {target_cr:g}x

DSP-only codec. There are no trained weights; this package ships the
bitstream contract plus a portable C99 implementation.

## Operating point

| Field         | Value           |
|---------------|-----------------|
| Modality      | {modality.upper()} |
| Sample rate   | {sample_rate} Hz |
| Frame size    | {frame_size} samples |
| Wavelet       | `{wavelet}` |
| DWT levels    | {levels} |
| Target CR     | {target_cr:g}× |
| Bit budget    | {max_bits} bits/frame |
| Entropy coder | {ac_note} |

## Files

* `deploy_manifest.json` — top-level manifest (`family: "spiht"`).
* `spiht_config.json` — codec parameters (language-neutral).
* `sample_stimulus.npz` — synthetic frames (`stimulus`, `(N, frame_size)`).
* `reference_vectors.npz` — encode/decode round-trip vectors.
* `c_sources/spiht.[ch]` — portable C99 reference.
* `c_sources/spiht_app_config.h` — codec-specific defines for this CR.
* `model_card.json`, `scorecard.json` — optional metadata.

## Python quickstart

```python
from compressionkit.runtime import load_codec

codec = load_codec("./")
frame = ...  # (frame_size,) float32
enc = codec.compress(frame)
recon = codec.decompress(enc)
```

## C quickstart

```c
#include "spiht_app_config.h"

float frame[APP_SPIHT_FRAME_SIZE];
uint8_t bitstream[APP_SPIHT_MAX_BYTES];
/* ... fill frame from sensor ... */
size_t nbits = spiht_encode_frame(&enc, bitstream, APP_SPIHT_MAX_BITS);
```
"""


def export_spiht_deploy(
    codec: SpihtCodec,
    *,
    output_dir: str | Path,
    model_name: str | None = None,
    model_version: str = "1.0",
    num_stimulus_samples: int = 8,
    stimulus_seed: int = 42,
    model_card_info: dict | None = None,
    scorecard_summary: dict | None = None,
) -> SpihtDeploymentArtifacts:
    """Export a SPIHT codec to a self-contained deploy directory.

    Args:
        codec: Hydrated :class:`SpihtCodec` describing the operating point.
        output_dir: Directory to write all deploy artifacts into.
        model_name: Override for the manifest ``model_name`` (defaults to
            ``codec.name``).
        model_version: Semantic version string written to the manifest.
        num_stimulus_samples: How many synthetic frames to generate.
        stimulus_seed: RNG seed for the synthetic stimulus.
        model_card_info: Optional dict merged into ``model_card.json``.
        scorecard_summary: Optional dict written to ``scorecard.json``.

    Returns:
        :class:`SpihtDeploymentArtifacts` with paths to every file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = SpihtDeploymentArtifacts(output_dir=output_dir)

    name = model_name or codec.name
    # Source of truth for codec parameters is the typed SpihtCodecConfig.
    cfg = codec.config.model_dump()
    # ``max_bits`` is derived (not part of the typed config) but is needed
    # by both the C header and consumers comparing against the bitstream.
    cfg["max_bits"] = codec.max_bits

    # 1. Synthetic stimulus + reference vectors (round-trip through Python ref).
    logger.info("Generating synthetic stimulus (%d frames)...", num_stimulus_samples)
    stimulus = generate_stimulus(
        modality=codec.modality,
        num_samples=num_stimulus_samples,
        frame_size=codec.frame_size,
        sample_rate=codec.sample_rate,
        seed=stimulus_seed,
    ).astype(np.float32, copy=False)

    artifacts.sample_stimulus = output_dir / "sample_stimulus.npz"
    np.savez_compressed(artifacts.sample_stimulus, stimulus=stimulus)

    logger.info("Computing reference encode/decode vectors...")
    payloads: list[np.ndarray] = []
    nbits_arr = np.zeros(stimulus.shape[0], dtype=np.int32)
    reconstructions = np.zeros_like(stimulus)
    for i, frame in enumerate(stimulus):
        enc: EncodedFrame = codec.compress(frame)
        if isinstance(enc.payload, (bytes, bytearray)):
            payload_bytes = bytes(enc.payload)
        elif isinstance(enc.payload, np.ndarray):
            payload_bytes = enc.payload.astype(np.uint8).tobytes()
        else:
            payload_bytes = bytes(enc.payload)
        payloads.append(np.frombuffer(payload_bytes, dtype=np.uint8))
        nbits_arr[i] = int(enc.nbits)
        reconstructions[i] = codec.decompress(enc)

    # Pack ragged payloads as an object-array + offsets for portability.
    max_len = max((p.size for p in payloads), default=0)
    packed = np.zeros((len(payloads), max_len), dtype=np.uint8)
    payload_lengths = np.zeros(len(payloads), dtype=np.int32)
    for i, p in enumerate(payloads):
        packed[i, : p.size] = p
        payload_lengths[i] = p.size

    artifacts.reference_vectors = output_dir / "reference_vectors.npz"
    np.savez_compressed(
        artifacts.reference_vectors,
        input_frames=stimulus,
        bitstreams=packed,
        bitstream_lengths_bytes=payload_lengths,
        nbits=nbits_arr,
        reconstructions=reconstructions,
    )

    # 2. spiht_config.json (language-neutral parameters).
    artifacts.spiht_config = output_dir / "spiht_config.json"
    with artifacts.spiht_config.open("w") as f:
        json.dump(cfg, f, indent=2)

    # 3. Vendor C sources.
    artifacts.c_sources_dir = output_dir / "c_sources"
    artifacts.c_sources_dir.mkdir(exist_ok=True)
    for fname in _C_SOURCE_FILES:
        src = _C_SOURCE_DIR / fname
        if not src.exists():
            raise FileNotFoundError(f"Vendored C source missing: {src}")
        shutil.copy2(src, artifacts.c_sources_dir / fname)

    artifacts.app_config_header = artifacts.c_sources_dir / "spiht_app_config.h"
    artifacts.app_config_header.write_text(
        _render_app_config_header(
            frame_size=codec.frame_size,
            levels=codec.levels,
            max_bits=codec.max_bits,
            use_ac=codec.use_ac,
            wavelet=codec.wavelet,
            modality=codec.modality,
            target_cr=codec.target_cr,
        )
    )

    # 4. Optional model card / scorecard.
    if model_card_info is not None:
        artifacts.model_card = output_dir / "model_card.json"
        with artifacts.model_card.open("w") as f:
            json.dump(model_card_info, f, indent=2)
    if scorecard_summary is not None:
        artifacts.scorecard = output_dir / "scorecard.json"
        with artifacts.scorecard.open("w") as f:
            json.dump(scorecard_summary, f, indent=2)

    # 5. README.
    artifacts.readme = output_dir / "README.md"
    artifacts.readme.write_text(
        _render_readme(
            modality=codec.modality,
            target_cr=codec.target_cr,
            wavelet=codec.wavelet,
            levels=codec.levels,
            frame_size=codec.frame_size,
            sample_rate=codec.sample_rate,
            max_bits=codec.max_bits,
            use_ac=codec.use_ac,
        )
    )

    # 6. Top-level manifest tying everything together.
    artifacts.manifest = output_dir / "deploy_manifest.json"
    manifest = {
        "manifest_version": MANIFEST_VERSION,
        "family": "spiht",
        "model_name": name,
        "model_version": model_version,
        "codec": cfg,
        "artifacts": artifacts.as_dict(),
        "model_card": model_card_info or {},
        "scorecard_summary": scorecard_summary or {},
    }
    with artifacts.manifest.open("w") as f:
        json.dump(manifest, f, indent=2)

    logger.info("SPIHT deploy package written to %s", output_dir)
    return artifacts
